site_name: Pero Pipes

nav:
  - Home: 
    - Home: index.md
    - Introduction:
      - File naming convention: general/file-naming-convention.md
      - Asset types: general/asset-types.md
      - About Thot: general/about-Thot.md
      - Adding data: general/adding-data.md
      - Running analysis: general/running-analysis.md
  - Common: 
    - overview: hierarchies/common hierarchy.md
    - root: containers/root.md
    - ↓: 
      - batch_group: containers/batch_group.md
      - ↓: 
        - batch: containers/batch.md
        - ↓:
          - EQE: containers/EQE.md
          - PL: containers/PL.md
          - MPP: containers/MPP.md
          - UV-VIS: containers/UV-VIS.md
          - ↓:
            - transmission: containers/transmission.md
            - reflection: containers/reflection.md 
  - Evap: 
    - overview: hierarchies/evap hierarchy.md
    - root: containers/root.md
    - ↓: 
      - batch_group: containers/batch_group.md
      - ↓: 
        - batch: containers/batch.md
        - ↓:
          - EQE: containers/EQE.md
          - evap_logs: containers/evap_logs.md
          - PL: containers/PL.md
          - MPP: containers/MPP.md
          - UV-VIS: containers/UV-VIS.md
          - ↓:
            - transmission: containers/transmission.md
            - reflection: containers/reflection.md 


theme:
    name: 'material'
    icon:
      logo: material/pipe
    features: 
      - navigation.tabs
      - navigation.expand
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  - footnotes
  - attr_list    
  # emoji_generator: !!python/name:materialx.emoji.to_svgt
  # - pymdownx.arithmatex
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
#  - pymdownx.emoji:
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  # - admonition
  - toc:
      permalink: true

plugins:
  - search
  - roamlinks 